{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "children" : [ {
    "name" : "Test defects",
    "children" : [ {
      "name" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=10001&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10d9bb4f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "children" : [ {
        "name" : "登录成功用例",
        "uid" : "60e0dbbfb44537cd",
        "parentUid" : "2ebddcaabb9768c187e2ec2ab126f14c",
        "status" : "broken",
        "time" : {
          "start" : 1622604546456,
          "stop" : 1622604546529,
          "duration" : 73
        },
        "flaky" : false,
        "parameters" : [ "{'case_name': '登录成功用例', 'url': '/uc/v1/login/local', 'data': {'appId': '10001', 'openId': '7282'}, 'except': {'code': 200, 'errCode': 0, 'errDesc': '成功'}}" ]
      } ],
      "uid" : "2ebddcaabb9768c187e2ec2ab126f14c"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=10001&openId= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dd750d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "children" : [ {
        "name" : "登录失败用例-openId为空",
        "uid" : "bb564608473c3274",
        "parentUid" : "1ca5a3a2411dbdb801fd409d8f587d98",
        "status" : "broken",
        "time" : {
          "start" : 1622604546797,
          "stop" : 1622604546804,
          "duration" : 7
        },
        "flaky" : false,
        "parameters" : [ "{'case_name': '登录失败用例-openId为空', 'url': '/uc/v1/login/local', 'data': {'appId': '10001', 'openId': ''}, 'except': {'code': 200, 'errCode': 1001, 'errDesc': 'openId为空'}}" ]
      } ],
      "uid" : "1ca5a3a2411dbdb801fd409d8f587d98"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dcf4670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "children" : [ {
        "name" : "登录失败用例-appId为空",
        "uid" : "ae072b881fb444dd",
        "parentUid" : "c44386b89a69cbaf8af7f3bd7193409f",
        "status" : "broken",
        "time" : {
          "start" : 1622604546996,
          "stop" : 1622604547007,
          "duration" : 11
        },
        "flaky" : false,
        "parameters" : [ "{'case_name': '登录失败用例-appId为空', 'url': '/uc/v1/login/local', 'data': {'appId': '', 'openId': '7282'}, 'except': {'code': 200, 'errCode': 1001, 'errDesc': 'appId为空'}}" ]
      } ],
      "uid" : "c44386b89a69cbaf8af7f3bd7193409f"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=test001&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dcc24c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "children" : [ {
        "name" : "登录失败用例-appId为字符",
        "uid" : "d7dde35a2b0db024",
        "parentUid" : "a7a04b1c7b29dc4fed539ee7745cc8ca",
        "status" : "broken",
        "time" : {
          "start" : 1622604547175,
          "stop" : 1622604547181,
          "duration" : 6
        },
        "flaky" : false,
        "parameters" : [ "{'case_name': '登录失败用例-appId为字符', 'url': '/uc/v1/login/local', 'data': {'appId': 'test001', 'openId': '7282'}, 'except': {'code': 200, 'errCode': 1001, 'errDesc': 'appId必须为大于等于0的整数'}}" ]
      } ],
      "uid" : "a7a04b1c7b29dc4fed539ee7745cc8ca"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=-100&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dd56970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "children" : [ {
        "name" : "登录失败用例-appId为负数",
        "uid" : "e71d0b79a0b1dd56",
        "parentUid" : "32bc8112332419b838f2c6b9fff311e0",
        "status" : "broken",
        "time" : {
          "start" : 1622604547340,
          "stop" : 1622604547347,
          "duration" : 7
        },
        "flaky" : false,
        "parameters" : [ "{'case_name': '登录失败用例-appId为负数', 'url': '/uc/v1/login/local', 'data': {'appId': '-100', 'openId': '7282'}, 'except': {'code': 200, 'errCode': 1001, 'errDesc': 'appId必须为大于等于0的整数'}}" ]
      } ],
      "uid" : "32bc8112332419b838f2c6b9fff311e0"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=0&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10de32130>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "children" : [ {
        "name" : "登录失败用例-appId为0",
        "uid" : "9b8e1f33a961dd36",
        "parentUid" : "9c18961c9dc562b12fc1214e86773e76",
        "status" : "broken",
        "time" : {
          "start" : 1622604547498,
          "stop" : 1622604547504,
          "duration" : 6
        },
        "flaky" : false,
        "parameters" : [ "{'case_name': '登录失败用例-appId为0', 'url': '/uc/v1/login/local', 'data': {'appId': '0', 'openId': '7282'}, 'except': {'code': 200, 'errCode': 1001, 'errDesc': 'appId必须大于0'}}" ]
      } ],
      "uid" : "9c18961c9dc562b12fc1214e86773e76"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=12345678912345678111122&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dc54b80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "children" : [ {
        "name" : "登录失败用例-appId为超长数字",
        "uid" : "f56c3feb86ece060",
        "parentUid" : "abf499f97f180cf290833cab60bce674",
        "status" : "broken",
        "time" : {
          "start" : 1622604547678,
          "stop" : 1622604547684,
          "duration" : 6
        },
        "flaky" : false,
        "parameters" : [ "{'case_name': '登录失败用例-appId为超长数字', 'url': '/uc/v1/login/local', 'data': {'appId': '12345678912345678111122', 'openId': '7282'}, 'except': {'code': 200, 'errCode': 1001, 'errDesc': 'appId太大'}}" ]
      } ],
      "uid" : "abf499f97f180cf290833cab60bce674"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=%40%23%23%EF%BF%A5%25%25%E2%80%A6%E2%80%A6&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ddd02e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "children" : [ {
        "name" : "登录失败用例-appId为特殊符号",
        "uid" : "534cecdf94363b0f",
        "parentUid" : "87bb95e1ac82d180f263b5237a597533",
        "status" : "broken",
        "time" : {
          "start" : 1622604547841,
          "stop" : 1622604547848,
          "duration" : 7
        },
        "flaky" : false,
        "parameters" : [ "{'case_name': '登录失败用例-appId为特殊符号', 'url': '/uc/v1/login/local', 'data': {'appId': '@##￥%%……', 'openId': '7282'}, 'except': {'code': 200, 'errCode': 1001, 'errDesc': 'appId必须为大于等于0的整数'}}" ]
      } ],
      "uid" : "87bb95e1ac82d180f263b5237a597533"
    }, {
      "name" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=10001&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dc3b1c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "children" : [ {
        "name" : "test_refreshtoken[refreshtoken0]",
        "uid" : "cef37db204c7477",
        "parentUid" : "ada81187566288ffb262b58fe1a308c5",
        "status" : "broken",
        "time" : {
          "start" : 1622604548026,
          "stop" : 1622604548026,
          "duration" : 0
        },
        "flaky" : false,
        "parameters" : [ "{'case_name': '成功用例', 'url': '/uc/v1/token', 'data': {'gid': '', 'refreshToken': ''}, 'except': {'code': 200, 'errCode': 0, 'errDesc': '成功'}}" ]
      }, {
        "name" : "test_refreshtoken[refreshtoken1]",
        "uid" : "847a42099511874b",
        "parentUid" : "ada81187566288ffb262b58fe1a308c5",
        "status" : "broken",
        "time" : {
          "start" : 1622604548199,
          "stop" : 1622604548199,
          "duration" : 0
        },
        "flaky" : false,
        "parameters" : [ "{'case_name': '失败用例-gid为空', 'url': '/uc/v1/token', 'data': {'gid': '', 'refreshToken': '38b3a3a6f-d6d6-5bac-afd2-523de4e3a86'}, 'except': {'code': 200, 'errCode': 1001, 'errDesc': 'gid为空'}}" ]
      }, {
        "name" : "test_refreshtoken[refreshtoken2]",
        "uid" : "95f283dc161dcab8",
        "parentUid" : "ada81187566288ffb262b58fe1a308c5",
        "status" : "broken",
        "time" : {
          "start" : 1622604548367,
          "stop" : 1622604548367,
          "duration" : 0
        },
        "flaky" : false,
        "parameters" : [ "{'case_name': '失败用例-登录已过期', 'url': '/uc/v1/token', 'data': {'gid': '86052724', 'refreshToken': 'wrong'}, 'except': {'code': 200, 'errCode': 1004, 'errDesc': '登录认证过期，请重新登录(10042)'}}" ]
      }, {
        "name" : "test_refreshtoken[refreshtoken3]",
        "uid" : "961930b00795b72c",
        "parentUid" : "ada81187566288ffb262b58fe1a308c5",
        "status" : "broken",
        "time" : {
          "start" : 1622604548529,
          "stop" : 1622604548529,
          "duration" : 0
        },
        "flaky" : false,
        "parameters" : [ "{'case_name': '失败用例-refreshToken为空', 'url': '/uc/v1/token', 'data': {'gid': '86052724', 'refreshToken': ''}, 'except': {'code': 200, 'errCode': 1001, 'errDesc': 'refreshToken为空'}}" ]
      }, {
        "name" : "test_refreshtoken[refreshtoken4]",
        "uid" : "544410b99ec1f14c",
        "parentUid" : "ada81187566288ffb262b58fe1a308c5",
        "status" : "broken",
        "time" : {
          "start" : 1622604548692,
          "stop" : 1622604548692,
          "duration" : 0
        },
        "flaky" : false,
        "parameters" : [ "{'case_name': '失败用例-gid为负数', 'url': '/uc/v1/token', 'data': {'gid': '-100', 'refreshToken': '38b3a3a6f-d6d6-5bac-afd2-523de4e3a86'}, 'except': {'code': 200, 'errCode': 1001, 'errDesc': 'gid必须为大于等于0的整数'}}" ]
      } ],
      "uid" : "ada81187566288ffb262b58fe1a308c5"
    } ],
    "uid" : "bdbf199525818fae7a8651db9eafe741"
  } ],
  "name" : "categories"
}