{
  "d84290471da0e863e23dcd83106411de" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "534cecdf94363b0f",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=%40%23%23%EF%BF%A5%25%25%E2%80%A6%E2%80%A6&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ddd02e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "time" : {
        "start" : 1622604547841,
        "stop" : 1622604547848,
        "duration" : 7
      }
    } ]
  },
  "d52540656c6faac35a0489825bef07a0" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "95f283dc161dcab8",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=10001&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dc3b1c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "time" : {
        "start" : 1622604548367,
        "stop" : 1622604548367,
        "duration" : 0
      }
    } ]
  },
  "95aec0a7ef36584074c69b1d05517faf" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "847a42099511874b",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=10001&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dc3b1c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "time" : {
        "start" : 1622604548199,
        "stop" : 1622604548199,
        "duration" : 0
      }
    } ]
  },
  "cf2376381e5f2b81aca9bb659321da16" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "9b8e1f33a961dd36",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=0&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10de32130>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "time" : {
        "start" : 1622604547498,
        "stop" : 1622604547504,
        "duration" : 6
      }
    } ]
  },
  "bbbdd29896c11ca033ff665066f390ba" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "f56c3feb86ece060",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=12345678912345678111122&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dc54b80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "time" : {
        "start" : 1622604547678,
        "stop" : 1622604547684,
        "duration" : 6
      }
    } ]
  },
  "49e81f0b821a18db02e3355b9455cbda" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "961930b00795b72c",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=10001&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dc3b1c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "time" : {
        "start" : 1622604548529,
        "stop" : 1622604548529,
        "duration" : 0
      }
    } ]
  },
  "62ebfc9838685827c6c77b9a9c19210a" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "bb564608473c3274",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=10001&openId= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dd750d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "time" : {
        "start" : 1622604546797,
        "stop" : 1622604546804,
        "duration" : 7
      }
    } ]
  },
  "460b021a806828955d107a1b53359a3a" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "60e0dbbfb44537cd",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=10001&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10d9bb4f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "time" : {
        "start" : 1622604546456,
        "stop" : 1622604546529,
        "duration" : 73
      }
    } ]
  },
  "9cf7f88f8675a2e363f32f1f2ace57e3" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "cef37db204c7477",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=10001&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dc3b1c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "time" : {
        "start" : 1622604548026,
        "stop" : 1622604548026,
        "duration" : 0
      }
    } ]
  },
  "a35b4f787259784e2713f3124ddd0c97" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "544410b99ec1f14c",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=10001&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dc3b1c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "time" : {
        "start" : 1622604548692,
        "stop" : 1622604548692,
        "duration" : 0
      }
    } ]
  },
  "6f7ef2ad2c83e080ab6592b83bc5f3cf" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "e71d0b79a0b1dd56",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=-100&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dd56970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "time" : {
        "start" : 1622604547340,
        "stop" : 1622604547347,
        "duration" : 7
      }
    } ]
  },
  "7a2d37de7b56400179c74bab79da7247" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "d7dde35a2b0db024",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=test001&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dcc24c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "time" : {
        "start" : 1622604547175,
        "stop" : 1622604547181,
        "duration" : 6
      }
    } ]
  },
  "a66607087936503960a2f33cfd10b293" : {
    "statistic" : {
      "failed" : 0,
      "broken" : 1,
      "skipped" : 0,
      "passed" : 0,
      "unknown" : 0,
      "total" : 1
    },
    "items" : [ {
      "uid" : "ae072b881fb444dd",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0,.1', port=8001): Max retries exceeded with url: /uc/v1/login/local?appId=&openId=7282 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dcf4670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))",
      "time" : {
        "start" : 1622604546996,
        "stop" : 1622604547007,
        "duration" : 11
      }
    } ]
  }
}